### ISSUE TITLE
rogue worker looping over a sleep 666ns, aka the quick delay in ringbuf wait loop

### ISSUE THREAD

**Issue by rixed** [rixed/ramen#1031]
Complete frame stack:
```
#0  0x00007ff0d6d952e0 in nanosleep () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00005624fa7052f7 in ringbuf_enqueue_commit ()
#2  0x00005624fa7000d9 in wrap_ringbuf_enqueue_commit ()
#3  0x00005624fa5012c1 in camlRingBufLib__fun_6655 ()
#4  0x00005624fa4c4cb8 in camlRamenHelpers__loop_2614 ()
#5  0x00005624fa6a89c1 in camlStdlib__list__iter_1148 () at list.ml:106
#6  0x00005624fa565a96 in camlCodeGenLib_Skeletons__do_out_8197 ()
#7  0x00005624fa566724 in camlCodeGenLib_Skeletons__aggregate_one_8241 ()
#8  0x00005624fa565d64 in camlCodeGenLib_Skeletons__fun_12100 ()
#9  0x00005624fa56772e in camlCodeGenLib_Skeletons__on_tup_8305 ()
#10 0x00005624fa4ffb44 in camlRingBufLib__loop_4526 ()
#11 0x00005624fa4c5c41 in camlRamenHelpers__log_exceptions_4782 ()
#12 0x00005624fa4ceb5e in camlRamenHelpers__finally_6477 ()
#13 0x00005624fa4ceb5e in camlRamenHelpers__finally_6477 ()
#14 0x00005624fa55be32 in camlCodeGenLib_Publish__start_zmq_client_simple_4851 ()
#15 0x00005624fa56232b in camlCodeGenLib_Skeletons__worker_start_7627 ()
#16 0x00005624fa4baec6 in camlM98c4c0e7454e6c14eccc3b88209b0c31_203e19f09432f869de6a2406b723e0d1_v65__worker_2679 ()
#17 0x00005624fa4914c8 in camlM98c4c0e7454e6c14eccc3b88209b0c31_casing_v65__entry ()
#18 0x00005624fa487369 in caml_program ()
#19 0x00005624facb4340 in caml_start_program ()
#20 0x00005624fac99045 in caml_startup_common (argv=0x7ffcbe5b1e68, pooling=<optimized out>, pooling@entry=0) at startup.c:157
#21 0x00005624fac9909b in caml_startup_exn (argv=<optimized out>) at startup.c:162
#22 caml_startup (argv=<optimized out>) at startup.c:167
#23 0x00005624fa4862dc in main (argc=<optimized out>, argv=<optimized out>) at main.c:44
```

Its outref is (now) empty BTW, which is expected. It must be trying to write on the notification or instrumenttion ringbuf. smaps reveal that it (`/srv/ramen/instrumentation_ringbuf/v9_v8/r is indeed stuck while writing into 
`/srv/ramen/notify_ringbuf/v7_v8/ringbuf.r`, stuck after 655 notifications:
```
nova@nightly:~$ ramen ringbuf /srv/ramen/notify_ringbuf/v7_v8/ringbuf.r
/srv/ramen/notify_ringbuf/v7_v8/ringbuf.r:
Flags:
seq range: 0..654 (655)
time range: 0.000000..1559109665.024075 (1559109665.0s)
0/1000000 words used (0.0%)
mmapped bytes: 4000064
producers range: 34330..34489
consumers range: 34330..34330
```

He was the only writer, given there is a single notification in the producer range:
```
nova@nightly:~$ ramen dump-ringbuf /srv/ramen/notify_ringbuf/v7_v8/ringbuf.r -f 34330 -t 34489

    6a 00 00 00 00 00 00 00 - 03 00 00 00 07 00 00 00    j...............
    6e 69 67 68 74 6c 79 00 - 2a 00 00 00 69 6e 74 65    nightly.*...inte
    72 6e 61 6c 2f 6d 6f 6e - 69 74 6f 72 69 6e 67 2f    rnal/monitoring/
    6d 65 74 61 2f 61 6c 65 - 72 74 5f 65 76 65 6e 74    meta/alert.event
    5f 74 69 6d 65 73 00 00 - 34 84 4d 02 ee 70 d7 41    .times..4.M..p.A
    00 00 00 99 ed 70 d7 41 - 17 00 00 00 49 6e 74 65    .....p.A....Inte
    72 6e 61 6c 20 2d 20 4c - 61 74 65 20 77 6f 72 6b    rnal.-.Late.work
    65 72 73 00 01 00 00 00 - 97 4f de f9 c1 37 b7 3f    ers......O...7.?
    06 00 00 00 00 00 00 00 - 00 00 00 00 05 00 00 00    ................
    73 74 61 72 74 00 00 00 - 0b 00 00 00 31 35 37 33    start.......1573
    31 30 37 33 30 30 2e 00 - 00 00 00 00 04 00 00 00    107300..........
    73 74 6f 70 0b 00 00 00 - 31 35 37 33 31 30 37 36    stop....15731076
    30 30 2e 00 00 00 00 00 - 11 00 00 00 65 76 65 6e    00..........even
    74 5f 74 69 6d 65 5f 73 - 70 72 65 61 64 00 00 00    t.time.spread...
    0d 00 00 00 37 37 33 37 - 33 2e 39 37 32 36 39 30    ....77373.972690
    31 00 00 00 00 00 00 00 - 04 00 00 00 64 65 73 63    1...........desc
    68 00 00 00 54 68 65 20 - 64 69 66 65 72 65 6e 63    h...The.diferenc
    65 20 62 65 74 77 65 65 - 6e 20 6f 6c 64 65 73 74    e.between.oldest
    20 28 24 7b 6d 69 6e 5f - 65 76 65 6e 74 5f 74 69    ..$.min.event.ti
    6d 65 7d 29 20 61 6e 64 - 20 6c 61 74 65 73 74 20    me...and.latest.
    28 24 7b 6d 61 78 5f 65 - 76 65 6e 74 5f 74 69 6d    .$.max.event.tim
    65 7d 29 20 65 76 65 6e - 74 20 74 69 6d 65 73 20    e...event.times.
    69 73 20 74 6f 6f 20 6c - 61 72 67 65 00 00 00 00    is.too.large....
    06 00 00 00 76 61 6c 75 - 65 73 00 00 0d 00 00 00    ....values......
    37 37 33 37 33 2e 39 37 - 32 36 39 30 31 00 00 00    77373.9726901...
    00 00 00 00 0a 00 00 00 - 74 68 72 65 73 68 6f 6c    ........threshol
    64 73 00 00 05 00 00 00 - 00 00 00 00 33 00 00 00    ds..........3...
    00 00 00 00 02 00 00 00 - 07 00 00 00 6e 69 67 68    ............nigh
    74 6c 79 00 2e 00 00 00 - 69 6e 74 65 72 6e 61 6c    tly.....internal
    2f 6d 6f 6e 69 74 6f 72 - 69 6e 67 2f 6d 65 74 61    /monitoring/meta
    2f 61 6c 65 72 74 5f 6f - 75 74 70 75 74 5f 64 6f    /alert.output.do
    5f 6e 6f 74 69 66 00 00 - 05 dd 56 79 ef 70 d7 41    .notif....Vy.p.A
    19 00 00 00 49 6e 74 65 - 72 6e 61 6c 20 2d 20 4f    ....Internal.-.O
    75 74 70 75 74 20 63 68 - 61 6e 67 65 64 00 00 00    utput.changed...
    00 00 00 00 9a 99 99 99 - 99 99 b9 3f 01 00 00 00    ...........?....
    00 00 00 00 00 00 00 00 - 04 00 00 00 64 65 73 63    ............desc
    31 00 00 00 4c 61 72 67 - 65 20 76 61 72 69 61 74    1...Large.variat
    69 6f 6e 73 20 69 6e 20 - 72 61 6d 65 6e 20 6e 75    ions.in.ramen.nu
    6d 62 65 72 20 6f 66 20 - 6f 75 74 70 75 74 20 74    mber.of.output.t
    75 70 6c 65 73 00 00 00 - 00 00 00 00                uples.......
```

Given it's not the first time that this worker is seen in this state, and it's very low output compared to others, it's probably safe to rule out a race condition.
Instead, as the written message has a deeper structure than the average one, we must suspect an encoding error.
How could an encoding error throw the worker in this deadloop though?
It is waiting for the tail to reach exactly the former position of the head. If the writer in charge of the previous tx died for any reasons (for instance, it tried to write past the alloced tx) then it will never advance the prod_tail and this worker is stuck forever.

So the previous notif was written by monitoring/meta/alert_event_times. According to the runtime stats, this worker had 0 (zero) output. Was it restarted? No all those meta monitoring workers started at the same time.

To begin with, this tight loop should exit after a few fractions of a second, as we are here waiting for one or two other writers to serialize a tuple.
Then, while bailing out, the worker should print what happened.

Is it possible that it is always that worker because it is always the same corrupted file?
Reference to the older ticket about that same process: https://github.com/rixed/ramen/issues/992
is from one month ago.

Killed that process, supervisor didn't notice. :-/  It's exit status in the config is written as "vanished".

**Comment by rixed** [comment]
Fixed by the above patch
