### ISSUE TITLE
assertion failed while painting status bar

### ISSUE THREAD

**Issue by rixed** [rixed/ramen#1044]
After a few minutes:
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff51c2535 in __GI_abort () at abort.c:79
#2  0x00007ffff5219508 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff532428d "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007ffff521fc1a in malloc_printerr (str=str@entry=0x7ffff532243b "free(): invalid pointer") at malloc.c:5341
#4  0x00007ffff522142c in _int_free (av=<optimized out>, p=<optimized out>, have_lock=<optimized out>) at malloc.c:4165
#5  0x00007ffff5d93a84 in QImage::~QImage() () from /lib/x86_64-linux-gnu/libQt5Gui.so.5
#6  0x00007ffff5e00234 in QFontEngine::unlockAlphaMapForGlyph() () from /lib/x86_64-linux-gnu/libQt5Gui.so.5
#7  0x00007ffff5f96830 in QRasterPaintEngine::drawCachedGlyphs(int, unsigned int const*, QFixedPoint const*, QFontEngine*) () from /lib/x86_64-linux-gnu/libQt5Gui.so.5
#8  0x00007ffff5f9a367 in QRasterPaintEngine::drawTextItem(QPointF const&, QTextItem const&) () from /lib/x86_64-linux-gnu/libQt5Gui.so.5
#9  0x00007ffff5fb214c in ?? () from /lib/x86_64-linux-gnu/libQt5Gui.so.5
#10 0x00007ffff5e376f0 in QTextLine::draw(QPainter*, QPointF const&, QTextLayout::FormatRange const*) const () from /lib/x86_64-linux-gnu/libQt5Gui.so.5
#11 0x00007ffff5fa86be in ?? () from /lib/x86_64-linux-gnu/libQt5Gui.so.5
#12 0x00007ffff5fa91e6 in QPainter::drawText(QRect const&, int, QString const&, QRect*) () from /lib/x86_64-linux-gnu/libQt5Gui.so.5
#13 0x00007ffff64bc3a5 in QStatusBar::paintEvent(QPaintEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#14 0x00007ffff635c4d8 in QWidget::event(QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#15 0x00007ffff64bd3e7 in QStatusBar::event(QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#16 0x00007ffff631e4c1 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#17 0x00007ffff6325970 in QApplication::notify(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#18 0x00007ffff59a34f9 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#19 0x00007ffff63550ca in QWidgetPrivate::sendPaintEvent(QRegion const&) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#20 0x00007ffff6355987 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) ()
   from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#21 0x00007ffff6356581 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#22 0x00007ffff635560c in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) ()
   from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#23 0x00007ffff632da9c in ?? () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#24 0x00007ffff632de19 in ?? () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#25 0x00007ffff63449d5 in QWidgetPrivate::syncBackingStore() () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#26 0x00007ffff635c608 in QWidget::event(QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#27 0x00007ffff6462d64 in QMainWindow::event(QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#28 0x00007ffff631e4c1 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#29 0x00007ffff6325970 in QApplication::notify(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#30 0x00007ffff59a34f9 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#31 0x00007ffff59a64db in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#32 0x00007ffff59f5173 in ?? () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#33 0x00007ffff4639f2e in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#34 0x00007ffff463a1c8 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#35 0x00007ffff463a25c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#36 0x00007ffff59f4797 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#37 0x00007ffff128b401 in ?? () from /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#38 0x00007ffff59a21cb in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#39 0x00007ffff59aa1a2 in QCoreApplication::exec() () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#40 0x00005555558f1b30 in main (argc=1, argv=0x7fffffffde68) at main.cpp:81
```

**Comment by rixed** [comment]
Seems fixed
